site_name: Listen
nav:
  - Python:
    - grammar: 
      - 函数: python/grammar/函数.md
      - 类: python/grammar/类.md
      - 装饰器: python/grammar/装饰器.md
    - Library: 
      - python/library/time.md
  - WebPage:
      - pass
  - Automated testing:
      - PyAutoGUI: testing/PyAutoGUI and pyperclip.md
  - Servers:
      - pass
  - Deploy:
    - Linux: deploy/Linux.md
    - Nginx: deploy/nginx.md
    - Docker: deploy/Docker.md
  - tool:
    - Git: tool/Git.md

theme:
  name: mkdocs
  locale: zh_CN
  user_color_mode_toggle: true

# markdown_extensions:
#   - toc:
#       permalink: "#"
#       baselevel: 1
#       separator: "_"
# nav_style: color_mode
extra_css:  
    - code.css

# hooks:
#   - my_hooks.py

  